-- US-06.1.2: Puanlama skalası (ör. 1-5) — sistem genelinde TEK bir skala
-- (roadmap'in "puanlama skalasını tanımlamak" ifadesi tekil; Goal/Competency'nin
-- aksine bu bir referans LİSTESİ değil, tek bir yapılandırma kaydı). Servis
-- seviyesinde upsert (find-or-create) ile "her zaman en fazla bir satır"
-- kuralı uygulanıyor — DB seviyesinde ayrıca bir kısıt gerekmiyor, tablo
-- pratikte hiçbir zaman ikinci bir satıra ulaşmıyor.

CREATE TABLE rating_scales (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    min_value     INTEGER                  NOT NULL,
    max_value     INTEGER                  NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(255)             NOT NULL,
    updated_by    VARCHAR(255)             NOT NULL
);
