// Bölüm 13.8: backend'deki TÜM `BaseEntity` alt sınıflarının (audit_log.
// entity_type olarak yazılan, bkz. AuditLogEntityListener#record ->
// entity.getClass().getSimpleName()) BİLİNEN listesi — filtre dropdown'u
// için statik olarak tutulur (backend bunu döndüren bir uç SUNMUYOR).
// Yeni bir varlık türü eklenirse buraya da eklenmelidir.
export const KNOWN_ENTITY_TYPES: string[] = [
  'Appointment',
  'AppointmentSlot',
  'ApprovalChainDefinition',
  'ApprovalChainInstance',
  'ApprovalChainStepDefinition',
  'AssessmentWeightConfig',
  'AttendanceRecord',
  'Award',
  'Candidate',
  'CandidateNote',
  'Club',
  'ClubEvent',
  'ClubMembershipRequest',
  'Competency',
  'CustomFieldDefinition',
  'CustomFieldValue',
  'DisciplinaryCase',
  'Employee',
  'EmployeeAsset',
  'EmployeeAssignmentHistory',
  'EmployeeProfile',
  'EmployeeSalaryRecord',
  'ExpenseItem',
  'Goal',
  'HiringRequest',
  'Interview',
  'JobDescription',
  'JobTitle',
  'LeaveRequest',
  'LeaveType',
  'ManagerAssessment',
  'ManagerAssessmentScore',
  'OrganizationUnit',
  'PayrollItem',
  'PolicyDocument',
  'RatingScale',
  'Role',
  'SelfAssessment',
  'SelfAssessmentScore',
  'ServiceOffering',
  'Session',
  'StaffingNorm',
  'StoredFile',
  'Suggestion',
  'SuggestionCategory',
  'Survey',
  'SurveyAnswer',
  'SurveyOption',
  'Training',
  'TrainingEnrollment',
  'TravelRequest',
  'User',
  'UserRole',
  'Warning',
  'WorkModel',
  'WorkModelAssignment',
].sort((a, b) => a.localeCompare(b, 'tr'))
