-- US-05.1.1: Birim/unvan bazlı norm kadro sayısı — "birim+unvan için sayısal
-- olarak tanımlanır" (kabul kriteri). Bir (birim, unvan) çiftinin tek bir norm
-- kaydı olur (upsert semantiği — bkz. StaffingNormService).
--
-- organization_unit_id/job_title_id'ye BİLİNÇLİ OLARAK DB seviyesinde FK
-- eklenMEDİ — recruitment modülü organization'a bağımlı değildir (yalnızca
-- core'a bağımlı mimari kuralı); bkz. leave modülünün V19 migration'ındaki
-- aynı gerekçe (leave_requests.employee_id).

CREATE TABLE staffing_norms (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_unit_id  BIGINT                   NOT NULL,
    job_title_id          BIGINT                   NOT NULL,
    norm_count            INTEGER                  NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by            VARCHAR(255)             NOT NULL,
    updated_by            VARCHAR(255)             NOT NULL,
    CONSTRAINT uq_staffing_norms_unit_title UNIQUE (organization_unit_id, job_title_id)
);
