-- US-05.2.2: Aday süreç aşaması (başvuru/mülakat/teklif/işe alım/ret) ve
-- aday profiline eklenen notlar (çoklu kayıt — bkz. CandidateNote).
-- Var olan (US-05.2.1'de oluşturulmuş) kayıtlar için varsayılan aşama
-- APPLICATION olarak geriye dönük dolduruluyor.

ALTER TABLE candidates
    ADD COLUMN stage VARCHAR(20) NOT NULL DEFAULT 'APPLICATION';

ALTER TABLE candidates
    ALTER COLUMN stage DROP DEFAULT;

CREATE TABLE candidate_notes (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id  BIGINT                   NOT NULL REFERENCES candidates(id),
    note_text     VARCHAR(2000)            NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(255)             NOT NULL,
    updated_by    VARCHAR(255)             NOT NULL
);
