-- US-07.1.1: Çalışma modeli (ör. "Tam Zamanlı", "Vardiyalı") — JobTitle'daki
-- (organization, US-03.1.2) AYNI "bağımsız, tekil bir referans listesi"
-- deseni: ilişkili olduğu vardiya/PDKS zenginliği (Feature 07.2) henüz
-- kurulmadığından, bu story yalnızca çalışana ATANABİLİR bir referans kaydı
-- tanımlamayı kapsıyor; gerçek atama US-07.1.2'de.

CREATE TABLE work_models (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255)             NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(255)             NOT NULL,
    updated_by    VARCHAR(255)             NOT NULL
);
