-- US-07.1.2: Bir çalışana atanmış çalışma modeli — organization.EmployeeProfile'daki
-- (V14) AYNI "employee_id üzerinde upsert, en fazla bir satır" deseni.
--
-- employee_id: organization.Employee'ye DB seviyesinde bir FK İLE değil düz
-- bir BIGINT olarak tutulur — attendance modülü organization'a bağımlı
-- olmadığından (modüller arası Java bağımlılığı yok kuralı) çalışanın
-- GERÇEKTEN var olup olmadığını burada doğrulayamıyoruz; bu, leave/performance
-- modüllerindeki employeeId alanlarıyla AYNI, kod içinde belgelenen güven
-- sınırı. work_model_id ise AYNI modül (attendance) içinde olduğundan normal
-- bir FK ile kısıtlanıyor.

CREATE TABLE work_model_assignments (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id    BIGINT                   NOT NULL UNIQUE,
    work_model_id  BIGINT                   NOT NULL REFERENCES work_models(id),
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by     VARCHAR(255)             NOT NULL,
    updated_by     VARCHAR(255)             NOT NULL
);
