-- US-09.7.1: Genel dosya saklama servisi (platform.file.FileStorageService) —
-- organization.PolicyDocument/recruitment.Candidate.cvData/travel.ExpenseItem'daki
-- (V23'te başlayan, sonra tekrarlanan) neredeyse özdeş "dosya bilgisi + VARBINARY
-- içerik" deseninin paylaşılan hali. Yalnızca YENİ ihtiyaçlar (ve bkz. ilgili
-- migration'daki travel.ExpenseItem taşıma örneği) bunu kullanır; PolicyDocument/
-- Candidate.cvData BİLİNÇLİ OLARAK taşınmadı (kendi versiyonlama/CV'ye özgü
-- mantıkları bu genellemeye zorla sığdırılırsa gereksiz regresyon riski olurdu).
CREATE TABLE stored_files (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name      VARCHAR(255)             NOT NULL,
    content_type   VARCHAR(255)             NOT NULL,
    file_data      BYTEA                    NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by     VARCHAR(255)             NOT NULL,
    updated_by     VARCHAR(255)             NOT NULL
);
