-- US-09.5.1: "Sistem yöneticisi olarak, kod değişikliği olmadan yeni bir
-- alan tanımlamak istiyorum." entity_type (ör. "Employee") + field_name
-- üzerinden, herhangi bir modülün varlığına parametrik bir alan ekleme
-- çerçevesi (EAV-lite) — projede zaten her yerde kullanılan FK'siz
-- modüller-arası güven sınırı desenine uygun (entity_id'nin hangi modülün
-- hangi tablosuna ait olduğu burada bilinmiyor, çağıran modül biliyor).
CREATE TABLE custom_field_definitions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type    VARCHAR(255)             NOT NULL,
    field_name     VARCHAR(255)             NOT NULL,
    field_type     VARCHAR(20)              NOT NULL,
    select_options VARCHAR(1000),
    required       BOOLEAN                  NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by     VARCHAR(255)             NOT NULL,
    updated_by     VARCHAR(255)             NOT NULL,
    UNIQUE (entity_type, field_name)
);

-- Tip fark etmeksizin tek bir değer kolonu (seyrek nullable kolonlar
-- yerine) — okuma anında custom_field_definitions.field_type'a göre
-- yorumlanır (bkz. CustomFieldValueService). Kolon adı "field_value" —
-- "value" hem H2 hem PostgreSQL'de ayrılmış (reserved) bir kelimedir.
CREATE TABLE custom_field_values (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    definition_id  BIGINT                   NOT NULL REFERENCES custom_field_definitions(id),
    entity_id      BIGINT                   NOT NULL,
    field_value    VARCHAR(1000),
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by     VARCHAR(255)             NOT NULL,
    updated_by     VARCHAR(255)             NOT NULL,
    UNIQUE (definition_id, entity_id)
);
