-- US-08A.1.2: Çalışanın katalogdan eğitim talebi — leave.LeaveRequest'teki
-- (V19) AYNI "talep→onay" deseninin tekrar kullanımı (roadmap Bölüm 4/5'teki
-- basit onay deseni; Bölüm 9.2'deki merkezi Onay Motoru henüz kurulmadı).
--
-- employee_id: organization.Employee'ye DB seviyesinde bir FK İLE değil düz
-- bir BIGINT olarak tutulur — leave/performance/attendance'taki AYNI
-- modüller-arası güven sınırı gerekçesi. training_id ise AYNI modül
-- içindeki trainings'e normal bir FK ile bağlı.

CREATE TABLE training_enrollments (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id        BIGINT                   NOT NULL,
    training_id        BIGINT                   NOT NULL REFERENCES trainings(id),
    status             VARCHAR(20)              NOT NULL,
    rejection_reason   VARCHAR(1000),
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by         VARCHAR(255)             NOT NULL,
    updated_by         VARCHAR(255)             NOT NULL
);
