-- US-03.3.1: Genişletilmiş özlük bilgileri (kimlik/adres/öğrenim/yabancı dil) —
-- Employee'nin temel bilgilerinden ayrı, isteğe bağlı bir "sekme/form" (1:1).
-- Tüm alanlar nullable: bu bilgiler zaman içinde, kademeli doldurulabilir.

CREATE TABLE employee_profiles (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id       BIGINT                   NOT NULL UNIQUE REFERENCES employees(id),
    birth_date        DATE,
    birth_place       VARCHAR(255),
    gender            VARCHAR(50),
    city              VARCHAR(255),
    district          VARCHAR(255),
    address_line      VARCHAR(500),
    education_level   VARCHAR(100),
    school_name       VARCHAR(255),
    graduation_year   INTEGER,
    foreign_language  VARCHAR(100),
    language_level    VARCHAR(50),
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by        VARCHAR(255)             NOT NULL,
    updated_by        VARCHAR(255)             NOT NULL
);
