-- US-03.3.2: Çalışana ait zimmet kayıtları (birden fazla kalem) — teslim/iade tarihi izlenir.
-- EmployeeProfile'ın (1:1) aksine burada employee_id UNIQUE DEĞİL: bir çalışanın
-- birden fazla zimmet kalemi (dizüstü bilgisayar, telefon, ...) olabilir.

CREATE TABLE employee_assets (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id   BIGINT                   NOT NULL REFERENCES employees(id),
    item_name     VARCHAR(255)             NOT NULL,
    delivered_at  DATE                     NOT NULL,
    returned_at   DATE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(255)             NOT NULL,
    updated_by    VARCHAR(255)             NOT NULL
);
