-- US-03.4.1: Çalışanın unvan/birim değişikliği geçmişi. Değişiklik anında eski
-- atama kapatılır (end_date doldurulur), yeni atama açılır (end_date NULL).
-- Tam "etkin-tarihli" (gelecek tarihli planlama) mimarisi henüz kurulmuyor —
-- yalnızca geçmişe dönük (o anki tarihle) kayıt tutuluyor.

CREATE TABLE employee_assignment_history (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id           BIGINT                   NOT NULL REFERENCES employees(id),
    organization_unit_id  BIGINT                   NOT NULL REFERENCES organization_units(id),
    job_title_id          BIGINT                   NOT NULL REFERENCES job_titles(id),
    start_date            DATE                     NOT NULL,
    end_date              DATE,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by            VARCHAR(255)             NOT NULL,
    updated_by            VARCHAR(255)             NOT NULL
);
