-- US-08I.1.1: Politika dokümanı yükleme + versiyonlama. Kabul kriteri:
-- "Yeni versiyon eskisini arşivler."
--
-- document_data: `recruitment.Candidate.cvData`'daki (V23) canlıda
-- yaşanan hatadan ders alınarak PROAKTİF olarak `@JdbcTypeCode(VARBINARY)`
-- ile eşlenecek (bkz. PolicyDocument entity javadoc'u) — düz bir BYTEA
-- sütunu, Hibernate'in PostgreSQL `oid` mekanizmasına eşlememesi için.
--
-- previous_version_id: AYNI tablo içinde kendine referans veren NULLABLE
-- bir FK — `discipline.DisciplinaryCase.caseId`'deki (US-08C.1.3) BENZER
-- fikir: NULL ise bu satır dokümanın İLK versiyonu; doluysa, işaret
-- ettiği id bir ÖNCEKİ (artık arşivlenmiş) versiyonun id'sidir. AMA
-- DisciplinaryCase'in AKSİNE burada eski satır GERÇEKTEN güncelleniyor
-- (status: ACTIVE→ARCHIVED) — kabul kriterinin "arşivler" ifadesi, bir
-- SEC-021 tipi değiştirilemezlik şartı değil, sıradan bir durum geçişi.

CREATE TABLE policy_documents (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                 VARCHAR(255)             NOT NULL,
    version               INTEGER                  NOT NULL,
    file_name             VARCHAR(255)             NOT NULL,
    content_type          VARCHAR(255)             NOT NULL,
    document_data         BYTEA                    NOT NULL,
    status                VARCHAR(20)              NOT NULL,
    previous_version_id   BIGINT REFERENCES policy_documents (id),
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by            VARCHAR(255)             NOT NULL,
    updated_by            VARCHAR(255)             NOT NULL
);
