-- US-08I.1.2: Unvan bazlı görev tanımı. Kabul kriteri: "Görev tanımı
-- unvana bağlanır."
--
-- job_title_id: diğer tüm modüllerdeki AYNI modüller-arası güven sınırı
-- gerekçesiyle FK'siz düz bir BIGINT — `document` modülü `organization`'a
-- bağımlı değil (yalnızca core'a bağımlı mimari kuralı).

CREATE TABLE job_descriptions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_title_id  BIGINT                   NOT NULL,
    content       VARCHAR(4000)            NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(255)             NOT NULL,
    updated_by    VARCHAR(255)             NOT NULL
);

CREATE INDEX idx_job_descriptions_job_title_id ON job_descriptions (job_title_id);
