-- US-03.1.1: Organizasyon birimleri (Şirket/İşyeri/Bölüm) ağaç yapısı.
-- Tip ayrımı (şirket/işyeri/bölüm) şimdilik zorunlu kılınmıyor (bkz. OrganizationUnit).

CREATE TABLE organization_units (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255)             NOT NULL,
    parent_id     BIGINT                   REFERENCES organization_units(id),
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(255)             NOT NULL,
    updated_by    VARCHAR(255)             NOT NULL
);
