-- US-03.2.1: Çalışan temel kaydı (ad-soyad, TC No, işe giriş tarihi, iletişim).
-- Birim/unvan ataması kasıtlı olarak burada yok (bkz. Employee) — US-03.2.2'de eklenecek.

CREATE TABLE employees (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR(255)             NOT NULL,
    last_name     VARCHAR(255)             NOT NULL,
    national_id   VARCHAR(11)              NOT NULL UNIQUE,
    hire_date     DATE                     NOT NULL,
    email         VARCHAR(255)             NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(255)             NOT NULL,
    updated_by    VARCHAR(255)             NOT NULL
);
