-- US-03.3.3: Çalışanın ücret/terfi geçmişi — SALT-EKLEME (append-only): yeni
-- kayıt eskisini silmez/güncellemez, geçmiş liste olarak görüntülenir.
-- EmployeeAsset'in aksine burada bir "durum değişikliği" (iade gibi) yok —
-- her satır kendi başına, değişmez bir geçmiş kaydı.

CREATE TABLE employee_salary_records (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id     BIGINT                   NOT NULL REFERENCES employees(id),
    amount          NUMERIC(12, 2)           NOT NULL,
    effective_date  DATE                     NOT NULL,
    reason          VARCHAR(255),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by      VARCHAR(255)             NOT NULL,
    updated_by      VARCHAR(255)             NOT NULL
);
