-- US-08E.1.2: Ankete yanıt verme; "anonim seçeneği varsa kullanıcı bilgisi
-- tutulmaz" (FR-704). `surveys.anonymous`, anketin İK tarafından
-- oluşturulurken "aktif edilebilir" (FR-704) opsiyonel anonimlik bayrağı —
-- var olan (US-08E.1.1'de oluşturulmuş) anketler için varsayılan FALSE
-- olarak geriye dönük dolduruluyor (`recruitment`'taki V24'teki AYNI
-- ALTER+DROP DEFAULT deseni).
--
-- survey_answers.employee_id NULLABLE: anonim bir ankette bilinçli olarak
-- HİÇ YAZILMIYOR (bkz. SurveyAnswerService) — "tutulmaz" kabul kriteri
-- yalnızca uygulama seviyesinde değil, şema seviyesinde de mümkün olmalı.
-- survey_id/survey_option_id, training.TrainingEnrollment.trainingId'deki
-- AYNI ayrımla AYNI modül içi varlıklara bağlandığından normal FK.

ALTER TABLE surveys
    ADD COLUMN anonymous BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE surveys
    ALTER COLUMN anonymous DROP DEFAULT;

CREATE TABLE survey_answers (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_id        BIGINT                   NOT NULL REFERENCES surveys (id),
    survey_option_id BIGINT                   NOT NULL REFERENCES survey_options (id),
    employee_id      BIGINT,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by       VARCHAR(255)             NOT NULL,
    updated_by       VARCHAR(255)             NOT NULL
);

CREATE INDEX idx_survey_answers_survey_id ON survey_answers (survey_id);
