-- US-08F.1.1: Kategori seçip talep/fikir gönderme. Kategori, kabul
-- kriterinin AÇIKÇA istediği gibi ("basit bir referans listesidir")
-- `organization.JobTitle`'daki AYNI minimal desen — yalnızca `name`, seed
-- data YOK (FR-801'in örnek kategorileri kasıtlı olarak taşınmadı; roadmap
-- kabul kriteri "hazır gelir" DEMİYOR, `auth.Role`'ün (US-02.2.1) AKSİNE).
--
-- suggestions.category_id: AYNI modül içindeki SuggestionCategory'e normal
-- bir FK ile bağlı; employee_id NULLABLE — FR-800'ün "opsiyonel anonim
-- gönderim" ihtiyacı için (bkz. Suggestion entity javadoc'u), diğer tüm
-- modüllerdeki employeeId'ler gibi modüller-arası bir FK OLMADAN.
--
-- Bu story'de HENÜZ bir `status` sütunu YOK — `travel.ExpenseItem`'in
-- (US-08B.1.2→US-08B.1.3) AYNI deseni: durum, yalnızca durum GÜNCELLEME
-- ihtiyacı ortaya çıktığında (US-08F.1.2) ayrı bir ALTER migration'la
-- eklenecek.

CREATE TABLE suggestion_categories (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255)             NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(255)             NOT NULL,
    updated_by    VARCHAR(255)             NOT NULL
);

CREATE TABLE suggestions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id   BIGINT                   NOT NULL REFERENCES suggestion_categories (id),
    employee_id   BIGINT,
    description   VARCHAR(2000)            NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(255)             NOT NULL,
    updated_by    VARCHAR(255)             NOT NULL
);

CREATE INDEX idx_suggestions_category_id ON suggestions (category_id);
CREATE INDEX idx_suggestions_employee_id ON suggestions (employee_id);
