-- US-08G.1.1: Kulüpleri görüntüleyip üyelik talebi oluşturma; talep İK
-- onayına gider. `performance`/`survey`/`suggestion`'daki (V28/V48/V50)
-- AYNI gerekçeyle, birlikte tanıtılan iki sıkı bağlı tablo TEK migration'da
-- oluşturuldu.
--
-- clubs: `organization.JobTitle`'daki AYNI minimal referans listesi
-- deseni — yalnızca `name`.
--
-- club_membership_requests: `leave.LeaveRequest`/`training.TrainingEnrollment`'daki
-- AYNI "talep→onay" deseni (PENDING/APPROVED/REJECTED). club_id, AYNI modül
-- içindeki Club'a normal bir FK ile bağlı; employee_id ise diğer tüm
-- modüllerdeki AYNI modüller-arası güven sınırı gerekçesiyle FK'siz düz bir
-- BIGINT.

CREATE TABLE clubs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255)             NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(255)             NOT NULL,
    updated_by    VARCHAR(255)             NOT NULL
);

CREATE TABLE club_membership_requests (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id           BIGINT                   NOT NULL REFERENCES clubs (id),
    employee_id       BIGINT                   NOT NULL,
    status            VARCHAR(20)              NOT NULL,
    rejection_reason  VARCHAR(1000),
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by        VARCHAR(255)             NOT NULL,
    updated_by        VARCHAR(255)             NOT NULL
);

CREATE INDEX idx_club_membership_requests_club_id ON club_membership_requests (club_id);
CREATE INDEX idx_club_membership_requests_employee_id ON club_membership_requests (employee_id);
