-- US-08G.1.2: "Kulüp Lideri olarak, etkinlik oluşturmak istiyorum. Etkinlik
-- yalnızca lider tarafından oluşturulabilir." `travel.ExpenseItem`'daki
-- (US-08B.1.2→US-08B.1.3) AYNI ALTER+DROP DEFAULT/nullable ADD COLUMN
-- deseni: clubs.leader_id, US-08G.1.1'de henüz yoktu — bu story'nin AÇIKÇA
-- gerektirdiği an eklendi. NULLABLE — bir kulübün lideri henüz atanmamış
-- olabilir (etkinlik oluşturma isteği o zaman kimseye izin vermeyecek
-- şekilde reddedilir, bkz. ClubEventService).
--
-- club_events.club_id: AYNI modül içindeki Club'a normal bir FK ile bağlı.

ALTER TABLE clubs ADD COLUMN leader_id BIGINT;

CREATE TABLE club_events (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id       BIGINT                   NOT NULL REFERENCES clubs (id),
    name          VARCHAR(255)             NOT NULL,
    event_date    DATE                     NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(255)             NOT NULL,
    updated_by    VARCHAR(255)             NOT NULL
);

CREATE INDEX idx_club_events_club_id ON club_events (club_id);
