-- US-08H.1.1: Hizmet ve uygun saat slotlarını tanımlama; slot çakışması
-- engellenir. `performance`/`survey`/`suggestion`/`club`'daki (V28/V48/V50/V52)
-- AYNI gerekçeyle, birlikte tanıtılan iki sıkı bağlı tablo TEK migration'da
-- oluşturuldu.
--
-- service_offerings: `organization.JobTitle`'daki AYNI minimal referans
-- listesi deseni — yalnızca `name`. FR-1201'in zengin alanları (kategori,
-- hizmet veren kişi, süre, günlük maks randevu sayısı, lokasyon, açıklama,
-- iptal süresi) BİLİNÇLİ OLARAK taşınmadı — kabul kriteri yalnızca "hizmet
-- ... tanımlamak" diyor.
--
-- appointment_slots: service_offering_id AYNI modül içindeki
-- ServiceOffering'e normal bir FK ile bağlı. Çakışma kontrolü (kabul
-- kriteri) DB seviyesinde bir CHECK/EXCLUDE kısıtı İLE değil, servis
-- seviyesinde uygulanıyor (bkz. AppointmentSlotService) — PostgreSQL'in
-- `EXCLUDE` kısıtı bu proje genelinde hiç kullanılmayan yeni bir kavram
-- getirirdi; `performance.Goal`'daki ("ağırlık toplamı" kuralı da DB
-- seviyesinde değil) AYNI YAGNI gerekçesi.

CREATE TABLE service_offerings (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255)             NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(255)             NOT NULL,
    updated_by    VARCHAR(255)             NOT NULL
);

CREATE TABLE appointment_slots (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_offering_id   BIGINT                   NOT NULL REFERENCES service_offerings (id),
    start_time            TIMESTAMP WITH TIME ZONE NOT NULL,
    end_time              TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by            VARCHAR(255)             NOT NULL,
    updated_by            VARCHAR(255)             NOT NULL
);

CREATE INDEX idx_appointment_slots_service_offering_id ON appointment_slots (service_offering_id);
