-- US-08H.1.2: Çalışanın bir slota randevu alması. Kabul kriteri: "Aynı
-- saatte ikinci randevu engellenir."
--
-- slot_id: AYNI modül içindeki AppointmentSlot'a normal bir FK ile bağlı.
-- employee_id: diğer tüm modüllerdeki AYNI modüller-arası güven sınırı
-- gerekçesiyle FK'siz düz bir BIGINT.
--
-- Bir slotun yalnızca BİR kez rezerve edilebilmesi (varsayılan kapasite=1
-- — FR-1202'nin "grup seansı" zenginliği taşınmadı) ve "aynı saatte ikinci
-- randevu" engeli DB seviyesinde bir UNIQUE/EXCLUDE kısıtı İLE değil,
-- servis seviyesinde uygulanıyor (bkz. AppointmentService) —
-- `appointment_slots`'taki (V54) AYNI YAGNI gerekçesi.

CREATE TABLE appointments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_id       BIGINT                   NOT NULL REFERENCES appointment_slots (id),
    employee_id   BIGINT                   NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(255)             NOT NULL,
    updated_by    VARCHAR(255)             NOT NULL
);

CREATE INDEX idx_appointments_slot_id ON appointments (slot_id);
CREATE INDEX idx_appointments_employee_id ON appointments (employee_id);
