-- US-07.2.1: PDKS'ten (Personel Devam Kontrol Sistemi) alınan fiili
-- giriş-çıkış verisi. Roadmap notu (YAGNI): bu, projenin ilk dış sistem
-- entegrasyonu — genel bir "adaptör çerçevesi" kurmak yerine, doğrudan
-- tek amaçlı bir içe aktarma uç noktası (bkz. AttendanceRecordController).
--
-- employee_id: organization.Employee'ye DB seviyesinde bir FK İLE değil düz
-- bir BIGINT olarak tutulur — work_model_assignments'taki (V35) AYNI
-- modüller-arası güven sınırı gerekçesi.
--
-- check_out_at NULLABLE: bir çalışan henüz çıkış yapmamışsa (gün ortasında
-- aktarılan veri) yalnızca giriş kaydı bilinir.

CREATE TABLE attendance_records (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id    BIGINT                   NOT NULL,
    check_in_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    check_out_at   TIMESTAMP WITH TIME ZONE,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by     VARCHAR(255)             NOT NULL,
    updated_by     VARCHAR(255)             NOT NULL
);
