-- US-04.2.1: İzin talebi (tür, tarih aralığı, durum). "Bekliyor" (PENDING)
-- durumuyla oluşturulur; onay/ret US-04.2.2'de ele alınacak.
--
-- employee_id'ye BİLİNÇLİ OLARAK DB seviyesinde FK (REFERENCES employees)
-- eklenMEDİ: leave modülü organization'a bağımlı değildir (yalnızca core'a
-- bağımlı mimari kuralı); employees tablosu farklı bir modülün şemasıdır ve
-- leave'in ona Java seviyesinde hiçbir görünürlüğü yok. Aynı fiziksel
-- veritabanı/şema kullanılıyor olması, modüller arası örtük bir FK bağımlılığı
-- kurmak için gerekçe değil — bu, Maven'in zorladığı derleme zamanı sınırını
-- veritabanı seviyesinde sessizce delerdi.
CREATE TABLE leave_requests (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id    BIGINT                   NOT NULL,
    leave_type_id  BIGINT                   NOT NULL REFERENCES leave_types(id),
    start_date     DATE                     NOT NULL,
    end_date       DATE                     NOT NULL,
    status         VARCHAR(20)              NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by     VARCHAR(255)             NOT NULL,
    updated_by     VARCHAR(255)             NOT NULL
);
