-- US-01.1.3: İlk Flyway migration'ı.
-- Bu migration'ın kapsamı, o ana kadar eklenmiş tek "gerçek" (test-dışı) varlık olan
-- AuditLogEntry (US-01.3.1) içindir. Hibernate ddl-auto artık "validate" olduğu için
-- şema yönetimi buradan sonra tamamen Flyway migration'ları üzerinden yapılır.

CREATE TABLE audit_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type   VARCHAR(255)             NOT NULL,
    entity_id     VARCHAR(255)             NOT NULL,
    operation     VARCHAR(50)              NOT NULL,
    performed_by  VARCHAR(255)             NOT NULL,
    performed_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_audit_log_entity ON audit_log (entity_type, entity_id);
