-- US-02.2.2: Kullanıcı-rol ataması (soft-invalidate: revoked_at).

CREATE TABLE user_roles (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT                   NOT NULL REFERENCES users (id),
    role_id       BIGINT                   NOT NULL REFERENCES roles (id),
    revoked_at    TIMESTAMP WITH TIME ZONE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(255)             NOT NULL,
    updated_by    VARCHAR(255)             NOT NULL
);

CREATE INDEX idx_user_roles_active ON user_roles (user_id, role_id) WHERE revoked_at IS NULL;
