-- US-04.1.1: İzin türleri (yıllık, mazeret vb.) — henüz genel bir parametrik
-- çerçeve değil, sabit alan setiyle basit bir tanım listesi.

CREATE TABLE leave_types (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255)             NOT NULL,
    code          VARCHAR(50)              NOT NULL UNIQUE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(255)             NOT NULL,
    updated_by    VARCHAR(255)             NOT NULL
);
