-- US-05.2.1: Aday başvurusu — harici (kimlik doğrulaması gerektirmeyen) bir
-- sayfadan temel bilgiler + CV dosyasıyla oluşturulur. CV, ayrı bir dosya
-- depolama servisi kurulmadan (bkz. roadmap Bölüm 9.7'nin "birden fazla
-- modülde tekrarlanınca genelleştir" tetikleyicisi — recruitment bunun İLK
-- kullanım yeri, henüz genelleştirme eşiği yok) doğrudan veritabanında
-- (bytea) tutuluyor; basit, tek bir dosya sahibi (aday) olduğundan bu yeterli.

CREATE TABLE candidates (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name        VARCHAR(255)             NOT NULL,
    last_name         VARCHAR(255)             NOT NULL,
    email             VARCHAR(255)             NOT NULL,
    applied_position  VARCHAR(255)             NOT NULL,
    cv_file_name      VARCHAR(255)             NOT NULL,
    cv_content_type   VARCHAR(100)             NOT NULL,
    cv_data           BYTEA                    NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by        VARCHAR(255)             NOT NULL,
    updated_by        VARCHAR(255)             NOT NULL
);
