-- US-05.3.1: İşe alım talebi — norm kadroyla uyumlu (bkz. staffing_norms;
-- norm yoksa talep servis seviyesinde engellenir, DB'de ayrıca bir FK/kontrol
-- kısıtına gerek yok). organization_unit_id/job_title_id'ye BİLİNÇLİ OLARAK
-- DB seviyesinde FK eklenMEDİ — recruitment modülü organization'a bağımlı
-- değildir; bkz. V22 migration'ındaki (staffing_norms) aynı gerekçe.
--
-- status, US-04.2.1'deki (leave_requests) aynı desen: PENDING durumuyla
-- oluşturulur, onay/ret US-05.3.2'de ele alınacak.

CREATE TABLE hiring_requests (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_unit_id  BIGINT                   NOT NULL,
    job_title_id          BIGINT                   NOT NULL,
    status                VARCHAR(20)              NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by            VARCHAR(255)             NOT NULL,
    updated_by            VARCHAR(255)             NOT NULL
);
