-- US-05.4.1: Aday mülakat kaydı (tarih/katılımcı/sonuç) — çoklu kayıt
-- (bir adayın birden fazla mülakatı olabilir), candidates ile AYNI modülde
-- olduğundan gerçek bir DB FK'ye sahip (bkz. candidate_notes'taki aynı
-- gerekçe, V24 migration'ı).

CREATE TABLE interviews (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id    BIGINT                   NOT NULL REFERENCES candidates(id),
    interview_date  DATE                     NOT NULL,
    participants    VARCHAR(500)             NOT NULL,
    result          VARCHAR(1000)            NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by      VARCHAR(255)             NOT NULL,
    updated_by      VARCHAR(255)             NOT NULL
);
