-- US-08B.1.1: Seyahat talebi (lokasyon, tarih aralığı, amaç) — roadmap
-- story metni FR-500'ün tam zenginliğini (tahmini maliyet vb.) DEĞİL,
-- yalnızca açıkça istenen üç alanı kapsıyor; kabul kriteri yalnızca
-- "Form kaydedilir" diyor, bir onay akışı bu story'de YOK (bkz. US-08B.1.3).
--
-- employee_id: organization.Employee'ye DB seviyesinde bir FK İLE değil düz
-- bir BIGINT olarak tutulur — leave/performance/attendance/training'teki
-- AYNI modüller-arası güven sınırı gerekçesi.

CREATE TABLE travel_requests (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id   BIGINT                   NOT NULL,
    location      VARCHAR(255)             NOT NULL,
    start_date    DATE                     NOT NULL,
    end_date      DATE                     NOT NULL,
    purpose       VARCHAR(1000)            NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(255)             NOT NULL,
    updated_by    VARCHAR(255)             NOT NULL
);
