-- US-08D.1.1: Temel ücret kalemlerini (maaş, kesinti) tanımlama. Kabul
-- kriteri: "Kalem tanımı basit bir referans listesidir." —
-- `organization.JobTitle`'daki AYNI minimal referans listesi deseni.
--
-- FR-1102'nin zengin, sabit ücret kalemi listesi (temel ücret, fazla
-- mesai, hafta tatili, UBGT, prim, ikramiye, yemek/yol yardımı, avans,
-- nafaka/icra/BES kesintileri, ...) BİLİNÇLİ OLARAK bir enum'a
-- DÖNÜŞTÜRÜLMEDİ — roadmap story metnindeki "(maaş, kesinti)" örnek
-- değerlerdir, `type` SERBEST METİN (`training.Training.type`'daki
-- (US-08A.1.1) AYNI gerekçe).

CREATE TABLE payroll_items (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255)             NOT NULL,
    type          VARCHAR(255)             NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(255)             NOT NULL,
    updated_by    VARCHAR(255)             NOT NULL
);
