-- US-06.1.1: Hedef/yetkinlik tanımlama (ad, ağırlık). "Hedef" ve "Yetkinlik"
-- organization.OrganizationUnit/JobTitle'daki AYNI desenle (roadmap Bölüm 3.1)
-- iki ayrı, basit referans listesi olarak modellendi — tek bir "tür" alanlı
-- ortak tablo yerine (bkz. Goal/Competency entity javadoc'undaki gerekçe).
--
-- Ağırlık toplamının 100'ü aşmaması kuralı (kabul kriteri: "ağırlık toplamı
-- validasyona tabidir") servis seviyesinde uygulanıyor, DB seviyesinde bir
-- CHECK kısıtı YOK — toplam, TÜM satırlar üzerinden hesaplanan bir kural,
-- tek bir satırın kendi başına doğrulayabileceği bir şey değil.

CREATE TABLE goals (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255)             NOT NULL,
    weight        INTEGER                  NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(255)             NOT NULL,
    updated_by    VARCHAR(255)             NOT NULL
);

CREATE TABLE competencies (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255)             NOT NULL,
    weight        INTEGER                  NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(255)             NOT NULL,
    updated_by    VARCHAR(255)             NOT NULL
);
