-- US-06.2.1: Öz değerlendirme — bir çalışanın, tanımlı hedef/yetkinlik seti
-- üzerinden kendi kendine verdiği puanlar. employee_id'ye BİLİNÇLİ OLARAK DB
-- seviyesinde FK eklenMEDİ — performance modülü organization'a bağımlı
-- değildir; bkz. leave/recruitment modüllerindeki aynı gerekçe (V19/V22).
--
-- self_assessment_scores.item_id, item_type'a (GOAL/COMPETENCY) göre AYRI
-- iki farklı tabloya (goals/competencies) işaret edebildiğinden tek bir FK
-- ile kısıtlanamıyor; referans bütünlüğü servis seviyesinde doğrulanıyor.

CREATE TABLE self_assessments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id   BIGINT                   NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(255)             NOT NULL,
    updated_by    VARCHAR(255)             NOT NULL
);

CREATE TABLE self_assessment_scores (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    self_assessment_id    BIGINT                   NOT NULL REFERENCES self_assessments(id),
    item_type             VARCHAR(20)              NOT NULL,
    item_id               BIGINT                   NOT NULL,
    score                 INTEGER                  NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by            VARCHAR(255)             NOT NULL,
    updated_by            VARCHAR(255)             NOT NULL
);
