-- US-06.2.2: Yönetici değerlendirmesi — SelfAssessment/SelfAssessmentScore
-- (US-06.2.1, V30) ile AYNI ŞEKİL ama BİLİNÇLİ OLARAK AYRI tablolar/kod —
-- "öz değerlendirme" ve "yönetici değerlendirmesi" farklı kavramlar,
-- projenin "aynı kod değil, benzer desende ayrı uygulama" konvansiyonu
-- (bkz. leave/recruitment onay adımlarındaki aynı yaklaşım).

CREATE TABLE manager_assessments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id   BIGINT                   NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(255)             NOT NULL,
    updated_by    VARCHAR(255)             NOT NULL
);

CREATE TABLE manager_assessment_scores (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manager_assessment_id  BIGINT                   NOT NULL REFERENCES manager_assessments(id),
    item_type              VARCHAR(20)              NOT NULL,
    item_id                BIGINT                   NOT NULL,
    score                  INTEGER                  NOT NULL,
    created_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by             VARCHAR(255)             NOT NULL,
    updated_by             VARCHAR(255)             NOT NULL
);
