-- US-06.2.3: Nihai not ağırlıklandırması (Hedef %/Yetkinlik %) — RatingScale
-- (V29) ile AYNI "sistem genelinde TEK yapılandırma kaydı" deseni: servis
-- seviyesinde upsert, DB seviyesinde ek bir kısıt gerekmiyor.

CREATE TABLE assessment_weight_configs (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goal_weight       INTEGER                  NOT NULL,
    competency_weight INTEGER                  NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by        VARCHAR(255)             NOT NULL,
    updated_by        VARCHAR(255)             NOT NULL
);
