-- US-02.1.3: Giriş sonrası oluşturulan oturumlar; çıkış işlemi revoked_at ile
-- geçersiz kılınır (fiziksel silme değil, bkz. Session.java notu).

CREATE TABLE sessions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token         VARCHAR(255)             NOT NULL UNIQUE,
    user_id       BIGINT                   NOT NULL REFERENCES users (id),
    expires_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at    TIMESTAMP WITH TIME ZONE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(255)             NOT NULL,
    updated_by    VARCHAR(255)             NOT NULL
);

CREATE INDEX idx_sessions_token ON sessions (token);
