-- US-02.2.1: Başlangıç rolleri (seed data) — Admin, İK, Yönetici, Çalışan.

CREATE TABLE roles (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(50)              NOT NULL UNIQUE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(255)             NOT NULL,
    updated_by    VARCHAR(255)             NOT NULL
);

INSERT INTO roles (code, created_at, updated_at, created_by, updated_by) VALUES
    ('ADMIN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system'),
    ('IK', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system'),
    ('YONETICI', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system'),
    ('CALISAN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'system', 'system');
