-- US-08C.1.1: Uyarı kaydı (tarih, sebep, açıklama) — roadmap story metni
-- FR-1301'in tam zenginliğini (veren kişi, kategori+serbest metin, ek
-- belge, çalışan savunması, geçerlilik süresi) DEĞİL, yalnızca açıkça
-- istenen üç alanı kapsıyor.
--
-- employee_id: organization.Employee'ye DB seviyesinde bir FK İLE değil düz
-- bir BIGINT olarak tutulur — diğer tüm modüllerdeki (leave/performance/
-- attendance/training/travel) AYNI modüller-arası güven sınırı gerekçesi.

CREATE TABLE warnings (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id   BIGINT                   NOT NULL,
    date          DATE                     NOT NULL,
    reason        VARCHAR(500)             NOT NULL,
    description   VARCHAR(2000)            NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(255)             NOT NULL,
    updated_by    VARCHAR(255)             NOT NULL
);
