-- US-08C.1.2: Ceza süreci kaydı — kabul kriteri yalnızca "ceza sürecini
-- kaydetmek" ve "çalışan savunması alınmadan süreç kapanmamalı" diyor.
-- FR-1304'ün tam zenginliği (disiplin kuruluna sevk, kurul üyeleri, çok
-- seviyeli onay, bildirim) BİLİNÇLİ OLARAK taşınmadı — US-08A.1.1'den beri
-- sürdürülen "roadmap'in basitleştirilmiş kabul kriterini uygula" konvansiyonu.
--
-- employee_id: diğer tüm modüllerdeki (leave/performance/attendance/
-- training/travel/discipline.Warning) AYNI modüller-arası güven sınırı
-- gerekçesiyle FK'siz düz bir BIGINT.
--
-- defense (savunma) NULLABLE: süreç açıldığında henüz alınmamış olabilir;
-- yalnızca kapatma anında zorunlu (bkz. DisciplinaryCaseService.close).

CREATE TABLE disciplinary_cases (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id   BIGINT                   NOT NULL,
    reason        VARCHAR(1000)            NOT NULL,
    defense       VARCHAR(2000),
    status        VARCHAR(20)              NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(255)             NOT NULL,
    updated_by    VARCHAR(255)             NOT NULL
);
