-- US-08C.1.4 (EPIC-08C tamamlandı): Ödül kaydı (takdir belgesi, prim vb.) —
-- roadmap story metni FR-1308'in tam zenginliğini (ödül türleri enum'u,
-- veren kişi, ek doküman) KASITLI OLARAK taşımadı; kabul kriteri yalnızca
-- "Kayıt çalışana bağlanır" diyor. `Warning`'deki (US-08C.1.1) AYNI
-- minimal desen: türü SERBEST METİN (`type`) — story metninin
-- "(takdir belgesi, prim vb.)" ifadesi sabit bir tür kümesi DEĞİL, örnek
-- değerler; bir enum icat etmek yanlış bir varsayım olurdu.
--
-- employee_id: diğer tüm modüllerdeki AYNI modüller-arası güven sınırı
-- gerekçesiyle FK'siz düz bir BIGINT.

CREATE TABLE awards (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id   BIGINT                   NOT NULL,
    type          VARCHAR(255)             NOT NULL,
    description   VARCHAR(2000)            NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(255)             NOT NULL,
    updated_by    VARCHAR(255)             NOT NULL
);
