-- US-09.2.1/US-09.2.2: Onay zinciri motoru — birden fazla modülün (İzin,
-- İşe Alım, ...) birbirinden bağımsız yazılmış onay kodlarını ortak,
-- parametrik bir motora taşıma tetikleyicisi. Yalnızca `recruitment`'ın
-- GERÇEK 2 aşamalı akışı (`HiringRequest`) buraya taşınıyor — leave/
-- training/travel/amenities'in tek-adımlı akışları (zaten
-- core.approval.ApprovalDecisionValidator ile deduplike) DOKUNULMADAN
-- bırakıldı, tek-adımlı bir akışı çok-adımlı bir motora zorlamak gereksiz
-- soyutlama olurdu.
CREATE TABLE approval_chain_definitions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255)             NOT NULL UNIQUE,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by   VARCHAR(255)             NOT NULL,
    updated_by   VARCHAR(255)             NOT NULL
);

-- US-09.2.2 kabul kriteri: "Zincir adım sayısı/onaylayıcı rolü ekrandan
-- yapılandırılır." Hiçbir modülde henüz bir admin ekranı olmadığından bu,
-- yalnızca bir REST API olarak karşılanıyor (bkz. ApprovalChainDefinitionController).
CREATE TABLE approval_chain_step_definitions (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chain_definition_id   BIGINT                   NOT NULL REFERENCES approval_chain_definitions(id),
    step_order            INTEGER                  NOT NULL,
    required_role         VARCHAR(255)             NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by            VARCHAR(255)             NOT NULL,
    updated_by            VARCHAR(255)             NOT NULL,
    UNIQUE (chain_definition_id, step_order)
);

-- subject_id BİLİNÇLİ OLARAK NULLABLE: bir örnek başlatılırken (start),
-- konu (ör. HiringRequest) henüz kendi id'sine sahip DEĞİL (o id, ZİNCİR
-- örneği kaydedildikten SONRA belli oluyor — bkz. HiringRequestService.create'teki
-- iki aşamalı kayıt). ApprovalChainService.assignSubject, id belli olduğunda
-- bu alanı geriye dönük dolduruyor.
CREATE TABLE approval_chain_instances (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chain_definition_id   BIGINT                   NOT NULL REFERENCES approval_chain_definitions(id),
    subject_type          VARCHAR(255)             NOT NULL,
    subject_id            BIGINT,
    current_step_order    INTEGER                  NOT NULL,
    status                VARCHAR(20)              NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by            VARCHAR(255)             NOT NULL,
    updated_by            VARCHAR(255)             NOT NULL
);
