-- US-08A.1.1: Eğitim kataloğu — attendance.WorkModel/organization.JobTitle'daki
-- AYNI bağımsız, tekil referans listesi deseni; ancak kabul kriterinin
-- açıkça istediği alan sayısı fazla (ad, tür, süre, sağlayıcı).

CREATE TABLE trainings (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(255)             NOT NULL,
    type             VARCHAR(100)             NOT NULL,
    duration_hours   INTEGER                  NOT NULL,
    provider         VARCHAR(255)             NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by       VARCHAR(255)             NOT NULL,
    updated_by       VARCHAR(255)             NOT NULL
);
