-- US-08B.1.2: Masraf kalemi — bir seyahat talebine (bkz. travel_requests,
-- V41) bağlı, tutar + belge (makbuz/fatura) ile beyan edilir. Kabul kriteri
-- yalnızca "tutar+belge" diyor; FR-504'teki masraf tipi zenginliği (roadmap
-- story metninde İSTENMEDİĞİNDEN) bu tabloya taşınmadı.
--
-- document_data: recruitment.candidates.cv_data'daki (V23, canlıda düzeltilen
-- hata) AYNI dersle @JdbcTypeCode(SqlTypes.VARBINARY) ile eşlenecek — @Lob
-- DEĞİL, aksi halde Hibernate bunu PostgreSQL'in oid mekanizmasına eşler ve
-- düz bir bytea sütunuyla şema doğrulaması canlıda başarısız olur.

CREATE TABLE expense_items (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    travel_request_id        BIGINT                   NOT NULL REFERENCES travel_requests(id),
    amount                   NUMERIC(12, 2)           NOT NULL,
    document_file_name       VARCHAR(255)             NOT NULL,
    document_content_type    VARCHAR(255)             NOT NULL,
    document_data            BYTEA                    NOT NULL,
    created_at               TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at               TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by               VARCHAR(255)             NOT NULL,
    updated_by               VARCHAR(255)             NOT NULL
);
