-- US-08E.1.1: Basit bir anket (soru + seçenek listesi) — `performance`
-- modülündeki (V28) AYNI gerekçeyle, birlikte tanıtılan iki sıkı bağlı
-- tablo tek migration'da oluşturuldu.
--
-- survey_options.survey_id: AYNI modül içindeki Survey'e normal bir FK ile
-- bağlı (organization.Employee'ye bağlanan employeeId'lerdeki modüller-arası
-- güven sınırı gerekçesi BURADA GEÇERLİ DEĞİL — training.TrainingEnrollment.trainingId'deki
-- AYNI ayrım).

CREATE TABLE surveys (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question      VARCHAR(1000)            NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(255)             NOT NULL,
    updated_by    VARCHAR(255)             NOT NULL
);

CREATE TABLE survey_options (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_id     BIGINT                   NOT NULL REFERENCES surveys (id),
    text          VARCHAR(500)             NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by    VARCHAR(255)             NOT NULL,
    updated_by    VARCHAR(255)             NOT NULL
);

CREATE INDEX idx_survey_options_survey_id ON survey_options (survey_id);
